### ISSUE TITLE
Animation Foreground , Background (wawe)

### ISSUE THREAD

**Issue by alpha-delta** [vitalii-andriiovskyi/ngx-owl-carousel-o#136]
HI,
Its possible to set custom style, like opacity / size, to elements that are not centered?
My idea is to create a wave effect among the owl-items
any suggestions?

Thanks so much

**Comment by vitalii-andriiovskyi** [comment]
Hi @alpha-delta 

Centered elements (`.owl-item`) get css-class `center`.
Active slides (that is visible slides) get css-class `active`.

You can put your HTML into `.owl-item` and then make your animation:
```html
  ...
   <ng-template carouselSlide>
      <div class="slide-wrapper">
            Slide HTML
      </div>
   </ng-template>
  ...
``` 

```css
.slide-wrapper {
  background: linear-gradient(to left, blue, blue);
  transition: all 0.3s;
}

.center .slide-wrapper {
  background: linear-gradient(to left, blue, red);
}

```

I didn't write css animation. I just used `transition` to show the idea. Of course you have to align time transition with `navSpeed` or `dotSpeed`.

You can also use `animate.css` to make effects. But it works only for case `items=1`.
