### ISSUE TITLE
Add the option to have custom css class as param

### ISSUE THREAD

**Issue by yelhouti** [vitalii-andriiovskyi/ngx-owl-carousel-o#227]
Some purchased themes cam directly with styles like this:
```css
.owl-carousel.nav-style-2 .owl-nav .owl-next {
    transform: rotate(180deg)!important;
    transform-origin: 15px 8px;
}
```

It would be great to have the option add nav-style-2 like this:
```html
<owl-carousel-o styleClass="nav-style-2 mb-0"
```
And have these used inside with something like: 
```html
<div [class]="styleClass" #owlCarousel
      [ngClass]="{
                  'owl-carousel': true,
                  'owl-theme': true, 
                  'owl-rtl': owlDOMData?.rtl,
                  'owl-loaded': owlDOMData?.isLoaded,
                  'owl-responsive': owlDOMData?.isResponsive,
                  'owl-drag': owlDOMData?.isMouseDragable,
                  'owl-grab': owlDOMData?.isGrab}"

```
